### ISSUE TITLE
Enhancement request - update so python versions > 3.10 can build

### ISSUE THREAD

**Issue by lucaswhipple-sfn** [PlusToolkit/ndicapi#42]
I have been working with a downstream fork of this library which has a python wrapper (https://github.com/SciKit-Surgery/scikit-surgerynditracker, which implements a python wheel builder in this fork: https://github.com/SciKit-Surgery/ndicapi)

This implementation works when installing with python <= python 3.10, but fails on later python versions. 

In discussion of this issue in that library (https://github.com/SciKit-Surgery/ndicapi/issues/9), it was noted that this may be an error with the source library. 

It appears there is an issue with two lines in the ndicapimodule.cxx source file in the NDICAPI fork that is used for this library.

  ndicapimodule.cxx(1751): error C2106: '=': left operand must be l-value
  ndicapimodule.cxx(1752): error C2106: '=': left operand must be l-value

Here is the environment I am working with:

    OS: Windows 11
    Python: 3.11
    Poetry: 1.7.1

Full error message below:

`• Installing ndicapi (3.2.10): Failed

  ChefBuildError                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              
  Backend subprocess exited when trying to invoke build_wheel                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                              
  running bdist_wheel                                                                                                                                                                                                                                                                                         
  running build                                                                                                                                                                                                                                                                                               
  running build_ext                                                                                                                                                                                                                                                                                           
  building 'ndicapy' extension                                                                                                                                                                                                                                                                                
  creating build                                                                                                                                                                                                                                                                                              
  creating build\temp.win-amd64-cpython-311                                                                                                                                                                                                                                                                   
  creating build\temp.win-amd64-cpython-311\Release                                                                                                                                                                                                                                                           
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USR~1\AppData\Local\Temp\tmp9cuji1zm\.venv\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpndicapi.cxx /Fobuild\temp.win-amd64-cpython-311\Release\ndicapi.obj
  ndicapi.cxx
  ndicapi.cxx(822): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USR~1\AppData\Local\Temp\tmp9cuji1zm\.venv\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpndicapi_math.cxx /Fobuild\temp.win-amd64-cpython-311\Release\ndicapi_math.obj
  ndicapi_math.cxx
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USR~1\AppData\Local\Temp\tmp9cuji1zm\.venv\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpndicapi_serial.cxx /Fobuild\temp.win-amd64-cpython-311\Release\ndicapi_serial.obj
  ndicapi_serial.cxx
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USR~1\AppData\Local\Temp\tmp9cuji1zm\.venv\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpndicapi_socket.cxx /Fobuild\temp.win-amd64-cpython-311\Release\ndicapi_socket.obj
  ndicapi_socket.cxx
  C:\Users\USR\AppData\Local\Temp\tmpo67ngh2_\ndicapi-3.2.10\ndicapi_socket_win32.cxx(31): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
  C:\Users\USR\AppData\Local\Temp\tmpo67ngh2_\ndicapi-3.2.10\ndicapi_socket_win32.cxx(34): warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
  C:\Users\USR\AppData\Local\Temp\tmpo67ngh2_\ndicapi-3.2.10\ndicapi_socket_win32.cxx(35): warning C4996: 'gethostbyaddr': Use getnameinfo() or GetNameInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USR~1\AppData\Local\Temp\tmp9cuji1zm\.venv\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpndicapi_thread.cxx /Fobuild\temp.win-amd64-cpython-311\Release\ndicapi_thread.obj
  ndicapi_thread.cxx
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\USR~1\AppData\Local\Temp\tmp9cuji1zm\.venv\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpndicapimodule.cxx /Fobuild\temp.win-amd64-cpython-311\Release\ndicapimodule.obj
  ndicapimodule.cxx
  ndicapimodule.cxx(63): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(162): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(312): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(314): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(323): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(415): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(419): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  ndicapimodule.cxx(720): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  ndicapimodule.cxx(782): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
  ndicapimodule.cxx(1751): error C2106: '=': left operand must be l-value
  ndicapimodule.cxx(1752): error C2106: '=': left operand must be l-value
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

**Comment by adamrankin** [comment]
In the else clause:
```
#if PY_MAJOR_VERSION <= 2
  PyNdicapiType.ob_type = &PyType_Type;
  PyNDIBitfield_Type.ob_type = &PyType_Type;
#else
  Py_TYPE(&PyNdicapiType) = &PyType_Type;
  Py_TYPE(&PyNDIBitfield_Type) = &PyType_Type;
#endif
```

but I'm not familiar with python wrapping in c++, so if you know how to fix it, please let me know

**Comment by lucaswhipple-sfn** [comment]
I personally don't really understand why that line is failing in python 3.11 but not in 3.10 and later; it's not clear to me what changed in the python wheel building process.

The error is getting invoked when running the command `python.exe setup.py sdist bdist_wheel --plat-name win32` and you can see from the test matrix in https://github.com/SciKit-Surgery/ndicapi/actions/runs/7553797753/job/20565325181 that it works in 3.10 but not in 3.11. 

The compiler error  C2106: '=': left operand must be l-value is not very useful and furthermore confuses me because it builds on lower python versions.

**Comment by thompson318** [comment]
I found here https://docs.python.org/3/c-api/type.html#c.PyTypeObject that this has "Changed in version 3.11:[Py_TYPE is changed to an inline static function. The parameter type is no longer const" which is probably the problem. I'm not sure what to do about it though.

**Comment by thompson318** [comment]
I managed to get it to build (on windows at least) by using 
Py_SET_TYPE(&PyNdicapiType, &PyType_Type);
Py_SET_TYPE(&PyNDIBitfield_Type, &PyType_Type);
So now there is a pre-built windows binary for py311 on [PyPi](https://pypi.org/project/ndicapi/3.7.0/#files). @lucaswhipple-sfn  could you please test it? 
If it is OK we could add it to the code with some appropriate if statements.

**Comment by adamrankin** [comment]
Of course, make a PR and I'll review/merge

**Comment by lucaswhipple-sfn** [comment]
@thompson318 Initial results are that the library imports successfully with this change, which suggests the change you proposed resolves the issue on my end. 

To replicate what I did to make this work, if anyone else has a similar issue:

1. Downloaded the .whl file from the link provided
2. Copied that into a directory in my project
3. Added the following line to my poetry dependencies:
```
[tool.poetry.dependencies]
ndicapi = {path = "wheels/ndicapi-3.7.0-cp311-cp311-win_amd64.whl"}
```
4. ran `poetry lock` and `poetry install`

After that, the library imported successfully.

Thank you both for your help on this issue, I will continue to test and evaluate, and report back if there are ongoing issues, but there appear to be n=2 instances where this change helped.

Good  catch on the change in the python spec in 3.11!

**Comment by lucaswhipple-sfn** [comment]
Further comment - I have successfully streamed tool data from a Vega XT on python 3.11 with this fix.

**Comment by adamrankin** [comment]
If anyone could test it on Linux, that would be great

**Comment by thompson318** [comment]
The change to Py_SET_TYPE breaks the Linux build, see [https://github.com/SciKit-Surgery/ndicapi/actions/runs/7572111115/job/20621174513#step:10:103](https://github.com/SciKit-Surgery/ndicapi/actions/runs/7572111115/job/20621174513#step:10:103). So this will need to be implemented with some IF conditions depending on python version and OS. I'll iterate on it until I get all OS builds passing then submit a PR.

**Comment by adamrankin** [comment]
Thanks

**Comment by thompson318** [comment]
I've rechecked this and updated my version with your latest code, I hadn't realised you'd already put the relevant if statements in the pre-processor code. I can confirm it all seems to be working well and you can close the issue. Thank you.

**Comment by adamrankin** [comment]
Great, thanks!
