### ISSUE TITLE
Compatability with Python 3.12

### ISSUE THREAD

**Issue by thompson318** [PlusToolkit/ndicapi#43]
I had a user trying to build with python 3.12. Currently fails with
ndicapimodule.cxx:29:41: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
   29 |   #define PY_INT_OBJECT_OB_IVAL(ob) ob->ob_digit[0]

https://github.com/SciKit-Surgery/ndicapi/actions/runs/7991400661/job/21822469379#step:9:379
